export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

//authen
export const AUTHENTICATION_START = 'AUTHENTICATION_START';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';
export const SET_USER = 'SET_USER';
export const SET_PATIENT = 'SET_PATIENT';

export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

//Booking
export const BOOKING_START = 'BOOKING_START';
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS';
export const BOOKING_FAIL = 'BOOKING_FAIL';

//doctor
export const GET_ALL_DOCTOR_OF_DEPARTMENT_START =
  'GET_ALL_DOCTOR_OF_DEPARTMENT_START';
export const GET_ALL_DOCTOR_OF_DEPARTMENT_SUCCESS =
  'GET_ALL_DOCTOR_OF_DEPARTMENT_SUCCESS';
export const GET_ALL_DOCTOR_OF_DEPARTMENT_FAIL =
  'GET_ALL_DOCTOR_OF_DEPARTMENT_FAIL';

// Department

export const GET_ALL_DEPARTMENT_START = 'GET_ALL_DEPARTMENT_START';
export const GET_ALL_DEPARTMENT_SUCCESS = 'GET_ALL_DEPARTMENT_SUCCESS';
export const GET_ALL_DEPARTMENT_FAIL = 'GET_ALL_DEPARTMENT_FAIL';
